version: '3.8'

networks:
  default:
      name: rag-network

services:
  rag-inference:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rag-inference
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
    networks:
      - default